const STORAGE_KEY = "venue-mini-crm-events";
const LOGIN_KEY = "venue-mini-crm-authenticated";
const statuses = ["Enquiry", "Quote sent", "Deposit paid", "Confirmed", "Completed", "Cancelled"];
const tabConfig = [
  { id: "client", label: "Client", fields: [["clientName", "Full name", "text", true], ["phone", "Phone", "tel"], ["email", "Email", "email"], ["heardFrom", "Heard from", "text"]] },
  { id: "event", label: "Event", fields: [["eventType", "Event type", "text", true], ["eventDate", "Date", "date", true], ["startTime", "Start time", "time"], ["endTime", "End time", "time"], ["adults", "Adults", "number"], ["children", "Children", "number"], ["status", "Status", "select", true, statuses]] },
  { id: "setup", label: "Setup", fields: [["tables", "Tables", "text"], ["chairs", "Chairs", "text"], ["layout", "Layout", "text"], ["colourTheme", "Colour theme", "text"], ["linenColour", "Linen colour", "text"], ["chairSash", "Chair sash", "text"], ["djRequired", "DJ required", "checkbox"], ["djNotes", "DJ notes", "textarea"], ["decorNotes", "Decor notes", "textarea"]] },
  { id: "catering", label: "Catering", fields: [["menuTier", "Menu tier", "text"], ["starter", "Starter", "text"], ["main", "Main", "text"], ["dessert", "Dessert", "text"], ["dietary", "Dietary requirements", "textarea"], ["cateringNotes", "Catering notes", "textarea"]] },
  { id: "bar", label: "Bar", fields: [["barPackage", "Bar package", "text"], ["welcomeDrink", "Welcome drink", "text"], ["softDrinks", "Free soft drinks included", "checkbox"], ["barNotes", "Bar notes", "textarea"]] },
  { id: "staffing", label: "Staffing", fields: [["fohCount", "FOH count", "number"], ["barStaffCount", "Bar staff count", "number"], ["kitchenStaffCount", "Kitchen staff count", "number"], ["staffingNotes", "Staffing notes", "textarea"]] },
  { id: "payments", label: "Payments", fields: [["totalValue", "Total value", "number"], ["depositDue", "Deposit due", "number"], ["depositReceived", "Deposit received", "checkbox"], ["depositReceivedDate", "Deposit received date", "date"], ["balanceDueDate", "Balance due date", "date"], ["balanceReceived", "Balance received", "checkbox"], ["balanceReceivedDate", "Balance received date", "date"], ["paymentNotes", "Payment notes", "textarea"]] },
  { id: "notes", label: "Notes", fields: [["generalNotes", "Internal notes", "textarea"]] },
];
const seedEvents = [
  { id: crypto.randomUUID(), clientName: "Amelia Carter", phone: "07123 456 900", email: "amelia@example.com", heardFrom: "Instagram", eventType: "Wedding", eventDate: "2026-06-06", startTime: "14:00", endTime: "00:30", adults: 92, children: 8, status: "Confirmed", layout: "Top table plus dancefloor", colourTheme: "Sage and ivory", menuTier: "Gold", barPackage: "Premium", totalValue: 9800, depositDue: 1500, depositReceived: true, depositReceivedDate: "2026-02-01", balanceDueDate: "2026-05-20", balanceReceived: false, generalNotes: "Final numbers confirmed. Balance needs chasing." },
  { id: crypto.randomUUID(), clientName: "Noah Singh", phone: "07900 111 222", email: "noah@example.com", heardFrom: "Friend referral", eventType: "Birthday", eventDate: "2026-06-18", startTime: "18:30", endTime: "23:30", adults: 70, children: 0, status: "Deposit paid", colourTheme: "Black and gold", menuTier: "Buffet", totalValue: 3600, depositDue: 500, depositReceived: true, depositReceivedDate: "2026-05-10", balanceDueDate: "2026-06-04", balanceReceived: false },
  { id: crypto.randomUUID(), clientName: "Priya Wilson", phone: "07777 333 444", email: "priya@example.com", heardFrom: "Website", eventType: "Corporate dinner", eventDate: "2026-07-03", startTime: "19:00", endTime: "22:30", adults: 48, children: 0, status: "Quote sent", menuTier: "Silver", totalValue: 5100, depositDue: 800, depositReceived: false, balanceDueDate: "2026-06-20", balanceReceived: false },
];
let events = loadEvents();
let selectedId = events[0]?.id;
let currentView = "dashboard";
let calendarRange = 1;
let calendarCursor = firstOfMonth(new Date());
const $ = (id) => document.querySelector(id);
const el = {
  loginView: $("#loginView"), appView: $("#appView"), loginForm: $("#loginForm"), logoutButton: $("#logoutButton"),
  dashboardNav: $("#dashboardNav"), calendarNav: $("#calendarNav"), paymentsNav: $("#paymentsNav"), archiveNav: $("#archiveNav"),
  dashboardView: $("#dashboardView"), calendarView: $("#calendarView"), paymentsView: $("#paymentsView"), archiveView: $("#archiveView"),
  eventList: $("#eventList"), detailPanel: $("#detailPanel"), detailTemplate: $("#detailTemplate"), searchInput: $("#searchInput"), statusFilter: $("#statusFilter"), typeFilter: $("#typeFilter"), fromDate: $("#fromDate"), toDate: $("#toDate"), calendarTitle: $("#calendarTitle"), calendarContent: $("#calendarContent"), paymentsList: $("#paymentsList"), archiveList: $("#archiveList")
};
$("#newEventButton").addEventListener("click", createEvent);
el.dashboardNav.addEventListener("click", () => setView("dashboard"));
el.calendarNav.addEventListener("click", () => setView("calendar"));
el.paymentsNav.addEventListener("click", () => setView("payments"));
el.archiveNav.addEventListener("click", () => setView("archive"));
$("#prevMonthButton").addEventListener("click", () => shiftCalendar(-1));
$("#nextMonthButton").addEventListener("click", () => shiftCalendar(1));
document.querySelectorAll("[data-range]").forEach((button) => button.addEventListener("click", () => { calendarRange = Number(button.dataset.range); render(); }));
el.loginForm.addEventListener("submit", (event) => { event.preventDefault(); localStorage.setItem(LOGIN_KEY, "true"); showApp(); });
el.logoutButton.addEventListener("click", () => { localStorage.removeItem(LOGIN_KEY); el.loginView.classList.remove("hidden"); el.appView.classList.add("hidden"); });
[el.searchInput, el.statusFilter, el.typeFilter, el.fromDate, el.toDate].forEach((control) => control.addEventListener("input", render));
el.paymentsList.addEventListener("click", handleAction);
el.archiveList.addEventListener("click", handleAction);
if (localStorage.getItem(LOGIN_KEY) === "true") showApp();
function showApp() { el.loginView.classList.add("hidden"); el.appView.classList.remove("hidden"); render(); }
function loadEvents() { return JSON.parse(localStorage.getItem(STORAGE_KEY) || "null") || seedEvents; }
function saveEvents() { localStorage.setItem(STORAGE_KEY, JSON.stringify(events)); }
function updateEvent(id, updater) { events = events.map((event) => event.id === id ? updater(event) : event); selectedId = id; saveEvents(); render(); }
function createEvent() { const event = { id: crypto.randomUUID(), clientName: "New enquiry", eventType: "Wedding", eventDate: today(), status: "Enquiry", depositReceived: false, balanceReceived: false }; events = [event, ...events]; selectedId = event.id; saveEvents(); render(); }
function setView(view) { currentView = view; render(); }
function render() { renderViewState(); populateTypes(); renderSummary(); renderEventList(); renderCalendar(); renderPayments(); renderArchive(); renderDetail(); }
function renderViewState() { [[el.dashboardView,"dashboard",el.dashboardNav],[el.calendarView,"calendar",el.calendarNav],[el.paymentsView,"payments",el.paymentsNav],[el.archiveView,"archive",el.archiveNav]].forEach(([view,name,nav]) => { view.classList.toggle("hidden", currentView !== name); nav.classList.toggle("active", currentView === name); }); }
function populateTypes() { const current = el.typeFilter.value; const types = [...new Set(events.map((event) => event.eventType).filter(Boolean))].sort(); el.typeFilter.innerHTML = '<option value="all">All event types</option>' + types.map((type) => `<option>${escapeHtml(type)}</option>`).join(""); el.typeFilter.value = types.includes(current) ? current : "all"; }
function filteredEvents() { return events.filter((event) => event.clientName.toLowerCase().includes(el.searchInput.value.trim().toLowerCase())).filter((event) => el.statusFilter.value === "all" || event.status === el.statusFilter.value).filter((event) => el.typeFilter.value === "all" || event.eventType === el.typeFilter.value).filter((event) => !el.fromDate.value || event.eventDate >= el.fromDate.value).filter((event) => !el.toDate.value || event.eventDate <= el.toDate.value).sort(byDate); }
function renderSummary() { const upcoming = events.filter((event) => event.eventDate >= today() && !["Cancelled", "Completed"].includes(event.status)); $("#summaryUpcoming").textContent = upcoming.length; $("#summaryDeposit").textContent = upcoming.filter((event) => !event.depositReceived).length; $("#summaryBalance").textContent = upcoming.filter(isBalanceDue).length; }
function renderEventList() { const visible = filteredEvents(); el.eventList.innerHTML = visible.length ? "" : '<p class="event-meta empty-state">No bookings match these filters.</p>'; visible.forEach((event) => { const card = document.createElement("button"); card.type = "button"; card.className = ["event-card", selectedId === event.id ? "selected" : "", isSoon(event) ? "soon" : "", isOverdue(event) ? "overdue" : ""].filter(Boolean).join(" "); card.innerHTML = `<span class="event-main"><span class="event-title">${escapeHtml(event.clientName)}</span><span class="event-meta">${escapeHtml(event.eventType || "Untitled event")} - ${formatDate(event.eventDate)}</span></span><span class="badge ${badgeClass(event.status)}">${escapeHtml(event.status)}</span><span class="event-meta stacked-meta"><span>${guestCount(event)} guests</span><span>${formatTimeRange(event)}</span></span><span class="badge ${paymentBadgeClass(event)}">${paymentStatus(event)}</span>`; card.addEventListener("click", () => { selectedId = event.id; render(); }); el.eventList.append(card); }); }
function renderCalendar() { document.querySelectorAll("[data-range]").forEach((button) => button.classList.toggle("active", Number(button.dataset.range) === calendarRange)); const start = firstOfMonth(calendarCursor), end = addMonths(start, calendarRange), visible = eventsInRange(start, end); el.calendarTitle.textContent = calendarRange === 1 ? formatMonthYear(start) : `${formatMonthYear(start)} - ${formatMonthYear(addMonths(end, -1))}`; el.calendarContent.innerHTML = ""; calendarRange === 1 ? renderMonth(start, visible) : renderCompactMonths(start, end); }
function renderMonth(monthStart, monthEvents) { const panel = document.createElement("section"); panel.className = "calendar-month-panel"; panel.innerHTML = `<div class="calendar-panel-header"><div><p class="eyebrow">Month planner</p><h3>${formatMonthYear(monthStart)}</h3></div><span class="booking-count">${monthEvents.length} bookings</span></div>`; const grid = document.createElement("div"); grid.className = "month-grid"; ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].forEach((day) => grid.insertAdjacentHTML("beforeend", `<div class="weekday-heading">${day}</div>`)); const offset = (monthStart.getDay() + 6) % 7; const gridStart = new Date(monthStart); gridStart.setDate(monthStart.getDate() - offset); for (let i = 0; i < 42; i++) { const date = new Date(gridStart); date.setDate(gridStart.getDate() + i); const key = dateKey(date); const dayEvents = monthEvents.filter((event) => event.eventDate === key); const cell = document.createElement("div"); cell.className = ["month-cell", date.getMonth() !== monthStart.getMonth() ? "outside-month" : "", key === today() ? "today" : "", dayEvents.length ? "has-events" : ""].filter(Boolean).join(" "); cell.innerHTML = `<div class="month-cell-day">${date.getDate()}</div><div class="month-cell-bookings"></div>`; const bookings = cell.querySelector(".month-cell-bookings"); dayEvents.forEach((event) => { const booking = document.createElement("button"); booking.type = "button"; booking.className = ["month-booking", selectedId === event.id ? "selected" : ""].filter(Boolean).join(" "); booking.innerHTML = `<span class="month-booking-type">${escapeHtml(event.eventType || "Event")}</span><strong>${escapeHtml(event.clientName)}</strong><span>${formatTimeRange(event)}</span>`; booking.addEventListener("click", () => { selectedId = event.id; render(); }); bookings.append(booking); }); grid.append(cell); } panel.append(grid); el.calendarContent.append(panel); }
function renderCompactMonths(start, end) { const grid = document.createElement("section"); grid.className = "calendar-compact-grid"; for (let month = new Date(start); month < end; month = addMonths(month, 1)) { const monthEvents = eventsInRange(month, addMonths(month, 1)); const card = document.createElement("article"); card.className = "calendar-compact-card"; card.innerHTML = `<div class="calendar-panel-header compact"><h3>${formatMonthYear(month)}</h3><span class="booking-count">${monthEvents.length}</span></div><div class="compact-booking-list"></div>`; const list = card.querySelector(".compact-booking-list"); if (!monthEvents.length) list.innerHTML = '<p class="event-meta">No bookings</p>'; monthEvents.forEach((event) => { const item = document.createElement("button"); item.type = "button"; item.className = "compact-booking"; item.textContent = `${formatDay(event.eventDate)} ${event.clientName}`; item.addEventListener("click", () => { selectedId = event.id; render(); }); list.append(item); }); grid.append(card); } el.calendarContent.append(grid); }
function renderPayments() { const active = events.filter((event) => !["Cancelled", "Completed"].includes(event.status)).sort((a,b) => (a.balanceDueDate || a.eventDate).localeCompare(b.balanceDueDate || b.eventDate)); $("#summaryOverduePayments").textContent = active.filter(isOverdue).length; $("#summaryAwaitingDepositPayments").textContent = active.filter((event) => !event.depositReceived).length; $("#summaryFullyPaidPayments").textContent = active.filter((event) => event.balanceReceived).length; el.paymentsList.innerHTML = active.length ? "" : '<p class="event-meta empty-state">No active payment records to show.</p>'; active.forEach((event) => managementCard(event, el.paymentsList, true)); }
function renderArchive() { const archived = events.filter((event) => ["Cancelled", "Completed"].includes(event.status)).sort((a,b) => b.eventDate.localeCompare(a.eventDate)); el.archiveList.innerHTML = archived.length ? "" : '<p class="event-meta empty-state">Completed and cancelled bookings will appear here.</p>'; archived.forEach((event) => managementCard(event, el.archiveList, false)); }
function managementCard(event, parent, payment) { const card = document.createElement("article"); card.className = ["management-card", selectedId === event.id ? "selected" : "", isOverdue(event) ? "overdue" : ""].filter(Boolean).join(" "); card.innerHTML = `<button class="management-main" type="button" data-action="select" data-id="${event.id}"><span><strong>${escapeHtml(event.clientName)}</strong><span class="event-meta">${escapeHtml(event.eventType || "Untitled event")} - ${formatDate(event.eventDate)}</span></span><span class="badge ${payment ? paymentBadgeClass(event) : badgeClass(event.status)}">${payment ? paymentStatus(event) : escapeHtml(event.status)}</span></button>${payment ? `<div class="payment-grid"><span><span class="metric-label">Total value</span><strong>${formatMoney(event.totalValue)}</strong></span><span><span class="metric-label">Deposit</span><strong>${event.depositReceived ? "Received" : formatMoney(event.depositDue)}</strong></span><span><span class="metric-label">Balance due</span><strong>${event.balanceDueDate ? formatDate(event.balanceDueDate) : "TBC"}</strong></span></div>` : ""}<div class="management-actions">${payment ? paymentButtons(event) + `<button class="ghost-button inline mini" type="button" data-action="complete" data-id="${event.id}">Complete</button>` : `<button class="ghost-button inline mini" type="button" data-action="restore" data-id="${event.id}">Restore to confirmed</button>`}</div>`; parent.append(card); }
function paymentButtons(event) { return `${!event.depositReceived ? `<button class="ghost-button inline mini" type="button" data-action="deposit" data-id="${event.id}">Mark deposit paid</button>` : ""}${!event.balanceReceived ? `<button class="ghost-button inline mini" type="button" data-action="balance" data-id="${event.id}">Mark balance paid</button>` : ""}`; }
function handleAction(event) { const button = event.target.closest("[data-action]"); if (!button) return; const id = button.dataset.id, action = button.dataset.action; if (action === "select") { selectedId = id; render(); return; } applyRecordAction(id, action); }
function renderDetail() { const event = events.find((item) => item.id === selectedId); if (!event) { el.detailPanel.innerHTML = '<div class="panel-empty"><p class="eyebrow">No record selected</p><h2>Create or select a booking</h2><p>Event details will appear here once a booking is selected.</p></div>'; return; } el.detailPanel.innerHTML = ""; const fragment = el.detailTemplate.content.cloneNode(true); fragment.querySelector("[data-field='title']").textContent = event.clientName; fragment.querySelector(".detail-header").after(recordActions(event)); const tabList = fragment.querySelector("#tabList"), panels = fragment.querySelector("#tabPanels"); tabConfig.forEach((tab, index) => { const button = document.createElement("button"); button.className = `tab-button ${index === 0 ? "active" : ""}`; button.type = "button"; button.textContent = tab.label; button.addEventListener("click", () => activateTab(tab.id)); tabList.append(button); const panel = document.createElement("section"); panel.className = `tab-panel ${index === 0 ? "active" : ""}`; panel.dataset.tab = tab.id; panel.innerHTML = `<h3>${tab.label}</h3>`; const grid = document.createElement("div"); grid.className = "form-grid"; if (tab.id === "payments" && isOverdue(event)) grid.insertAdjacentHTML("beforeend", '<div class="payment-alert wide">Balance is overdue and has not been marked as received.</div>'); tab.fields.forEach((field) => grid.append(renderField(field, event))); panel.append(grid); panels.append(panel); }); fragment.querySelector("#deleteEventButton").addEventListener("click", () => deleteEvent(event)); fragment.querySelector("#cancelEditButton").addEventListener("click", renderDetail); fragment.querySelector("#eventForm").addEventListener("submit", (submit) => saveSelectedEvent(submit, event.id)); el.detailPanel.append(fragment); }
function recordActions(event) { const wrap = document.createElement("div"); wrap.className = "record-actions"; [["deposit","Deposit paid",!event.depositReceived],["balance","Balance paid",!event.balanceReceived],["complete","Complete",event.status !== "Completed"],["cancel","Cancel booking",event.status !== "Cancelled"],["restore","Restore",["Cancelled","Completed"].includes(event.status)]].filter((x) => x[2]).forEach(([action,label]) => { const button = document.createElement("button"); button.className = `ghost-button inline mini ${action === "cancel" ? "danger-text" : ""}`; button.type = "button"; button.textContent = label; button.addEventListener("click", () => applyRecordAction(event.id, action)); wrap.append(button); }); return wrap; }
function renderField([name,label,type,required=false,options=[]], event) { if (type === "checkbox") { const wrap = document.createElement("label"); wrap.className = "check-row"; wrap.innerHTML = `<input name="${name}" type="checkbox" ${event[name] ? "checked" : ""} /> ${label}`; return wrap; } const wrap = document.createElement("label"); if (type === "textarea") wrap.classList.add("wide"); const req = required ? "required" : "", value = event[name] ?? ""; if (type === "select") wrap.innerHTML = `${label}<select name="${name}" ${req}>${options.map((option) => `<option ${option === value ? "selected" : ""}>${option}</option>`).join("")}</select>`; else if (type === "textarea") wrap.innerHTML = `${label}<textarea name="${name}" ${req}>${escapeHtml(value)}</textarea>`; else wrap.innerHTML = `${label}<input name="${name}" type="${type}" value="${escapeHtml(value)}" ${req} />`; return wrap; }
function activateTab(id) { document.querySelectorAll(".tab-button").forEach((button) => button.classList.remove("active")); document.querySelectorAll(".tab-panel").forEach((panel) => panel.classList.remove("active")); const index = tabConfig.findIndex((tab) => tab.id === id); document.querySelectorAll(".tab-button")[index].classList.add("active"); document.querySelector(`[data-tab="${id}"]`).classList.add("active"); }
function saveSelectedEvent(event, id) { event.preventDefault(); const data = new FormData(event.currentTarget), next = {}; tabConfig.flatMap((tab) => tab.fields).forEach(([name,,type]) => { next[name] = type === "checkbox" ? data.has(name) : type === "number" ? (data.get(name) === "" ? "" : Number(data.get(name))) : data.get(name)?.toString() ?? ""; }); events = events.map((item) => item.id === id ? { ...item, ...next } : item); saveEvents(); render(); }
function applyRecordAction(id, action) { if (action === "cancel" && !confirm("Mark this booking as cancelled?")) return; const map = { deposit: (x) => ({...x, depositReceived:true, depositReceivedDate:x.depositReceivedDate || today(), status:["Enquiry","Quote sent"].includes(x.status) ? "Deposit paid" : x.status}), balance: (x) => ({...x, depositReceived:true, depositReceivedDate:x.depositReceivedDate || today(), balanceReceived:true, balanceReceivedDate:x.balanceReceivedDate || today(), status:["Enquiry","Quote sent","Deposit paid"].includes(x.status) ? "Confirmed" : x.status}), complete: (x) => ({...x,status:"Completed"}), cancel: (x) => ({...x,status:"Cancelled"}), restore: (x) => ({...x,status:"Confirmed"}) }; updateEvent(id, map[action]); }
function deleteEvent(event) { if (!confirm(`Delete ${event.clientName}'s booking? This cannot be undone.`)) return; events = events.filter((item) => item.id !== event.id); selectedId = events[0]?.id; saveEvents(); render(); }
function today(){return new Date().toISOString().slice(0,10)}
function firstOfMonth(date){return new Date(date.getFullYear(),date.getMonth(),1)}
function addMonths(date,count){return new Date(date.getFullYear(),date.getMonth()+count,1)}
function shiftCalendar(months){calendarCursor=addMonths(calendarCursor,months);render()}
function dateKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function eventsInRange(startDate,endDate){const start=dateKey(startDate),end=dateKey(endDate);return events.filter((e)=>e.status!=="Cancelled"&&e.eventDate>=start&&e.eventDate<end).sort(byDate)}
function byDate(a,b){return a.eventDate.localeCompare(b.eventDate)||(a.startTime||"").localeCompare(b.startTime||"")}
function isSoon(event){const days=(new Date(`${event.eventDate}T00:00:00`)-new Date(`${today()}T00:00:00`))/86400000;return days>=0&&days<=14}
function isBalanceDue(event){return event.balanceDueDate&&!event.balanceReceived}
function isOverdue(event){return event.balanceDueDate&&event.balanceDueDate<today()&&!event.balanceReceived}
function paymentStatus(event){if(isOverdue(event))return"Overdue";if(event.balanceReceived)return"Fully paid";if(event.depositReceived)return"Deposit paid";return"Unpaid"}
function paymentBadgeClass(event){return badgeClass(paymentStatus(event))}
function badgeClass(value=""){return value.toLowerCase().replace(/\s+/g,"-")}
function guestCount(event){return Number(event.adults||0)+Number(event.children||0)}
function formatDate(value){return value?new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${value}T00:00:00`)):"No date"}
function formatMonthYear(date){return new Intl.DateTimeFormat("en-GB",{month:"long",year:"numeric"}).format(date)}
function formatDay(value){return value?new Intl.DateTimeFormat("en-GB",{day:"2-digit"}).format(new Date(`${value}T00:00:00`)):"--"}
function formatTimeRange(event){if(event.startTime&&event.endTime)return`${event.startTime}-${event.endTime}`;if(event.startTime)return`From ${event.startTime}`;if(event.endTime)return`Until ${event.endTime}`;return"Time TBC"}
function formatMoney(value){const amount=Number(value);return value===""||value==null||Number.isNaN(amount)?"TBC":`\u00a3${amount.toLocaleString("en-GB")}`}
function escapeHtml(value=""){return value.toString().replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
